global using Microsoft.AspNetCore.Builder;
global using MyKitchen.Data;
global using System;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Azure.KeyVault;
global using Microsoft.Azure.Services.AppAuthentication;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Configuration.AzureKeyVault;
